# action.yml
name: "Copy to repo"
description: "Copy build files to another repository"
inputs:
    api-token-github:
        description: "API gitbug token"
        required: true
    source-directory:
        description: "Source dir"
        required: true
    destination-github-username:
        description: "destination repo username"
        required: true
    destination-repository-name:
        description: "destination repo name"
        required: true
    user-email:
        description: "vigneshe1992@gmail.com"
        required: false
        default: "vigneshe1992@gmail.com"
    user-name:
        description: "user name"
        required: false
        default: "devevignesh"
    destination-repository-username:
        description: "dest repo username"
        required: false
        default: ""
    target-branch:
        description: 'set target branch name for the destination repository. Defaults to "master"'
        default: "master"
        required: false
    commit-message:
        description: "commit message for the output repository."
        default: "release"
        required: false
runs:
    using: "docker"
    image: "Dockerfile"
    args:
        - ${{ inputs.source-directory }}
        - ${{ inputs.destination-github-username }}
        - ${{ inputs.destination-repository-name }}
        - ${{ inputs.user-email }}
        - ${{ inputs.user-name }}
        - ${{ inputs.destination-repository-username }}
        - ${{ inputs.target-branch }}
        - ${{ inputs.commit-message }}
        - ${{ inputs.api-token-github }}
